wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.0
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716515696
    t:
      1:
      - 1
      - 55
      - 105
      2:
      - 1
      - 11
      - 49
      - 55
      - 105
      3:
      - 13
      - 23
      4: 3.11.9
      5: 0.17.0
      8:
      - 4
      - 5
      13: darwin-arm64
